onlyBuiltDependencies:
  - "@parcel/watcher"
  - electron-winstaller
  - electron
  - esbuild

minimumReleaseAgeExclude:
  - antd@6.4.5

allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  electron-winstaller: true
